import { defineStore } from 'pinia'

export const useLanguageStore = defineStore('language', {
  state: () => ({
    language: 'zh'
  }),
  
  getters: {
    languageLabel: (state) => {
      return state.language === 'en' ? 'English' : '中文'
    },
    
    texts: (state) => {
      const zh = {
        login: {
          title: '登录',
          accountName: 'mixware账户',
          loginTab: '登录',
          loginByCodeTab: '验证码登录',
          passwordLoginTab: '密码登录',
          registerTab: '注册',
          usernameLabel: '用户名',
          usernamePlaceholder: '请输入用户名',
          emailLabel: '邮箱',
          emailPlaceholder: '请输入邮箱地址',
          codeLabel: '验证码',
          codePlaceholder: '请输入验证码',
          getCode: '获取验证码',
          passwordLabel: '密码',
          passwordPlaceholder: '请输入密码',
          confirmPasswordLabel: '确认密码',
          confirmPasswordPlaceholder: '请再次输入密码',
          birthdayLabel: '生日',
          birthdayPlaceholder: '请选择生日',
          marketingConsent: '同意接收营销推送信息',
          loginButton: '登录',
          registerButton: '注册',
          forgetPassword: '忘记密码',
          noAccount: '还没有账号?',
          registerNow: '立即注册',
          enterEmail: '请输入邮箱',
          enterPassword: '请输入密码',
          enterUsername: '请填写用户名',
          enterCode: '请填写验证码',
          confirmPassword: '请确认密码',
          passwordsNotMatch: '两次密码不一致',
          agreeToTerms: '请先阅读并同意用户协议',
          loginSuccess: '登录成功',
          loginFailed: '登录失败',
          registerSuccess: '注册成功',
          registerFailed: '注册失败',
          emailExists: '邮箱已存在',
          codeError: '验证码错误',
          codeExpired: '验证码已过期',
          sendCodeFailed: '发送验证码失败',
          thirdPartyLogin: '第三方登录',
          googleLogin: 'Google登录',
          googleLoginFailed: 'Google登录失败',
          readAndAgree: '我已阅读',
          userAgreement: '《用户协议》',
          privacyNotice: '《隐私通知》',
          mixwareAgreement: '《mixware用户协议》'
        },
        create: {
          title: '创作',
          allFunction: '全部功能',
          allDesc: '体验所有创作工具',
          photography: '拍一拍',
          photographyDesc: '拍照生成3D模型',
          chat: '说一说',
          chatDesc: '对话生成3D模型',
          textToModel: '文生模型',
          promptPlaceholder: '请输入描述，例如：一只可爱的小猫',
          pleaseInputPrompt: '请输入描述',
          aiChat: 'AI对话',
          aiChatDesc: '智能AI助手对话',
          aiChatPlaceholder: 'AI对话功能开发中',
          draw: '画一画',
          drawDesc: '涂鸦生成3D模型',
          uploadModel: '上传模型',
          transform: '变一变',
          transformDesc: '根据模型调整参数生成模型',
          mainView: '主视图',
          clickUpload: '点击上传主视图',
          clickChangeImage: '点击更换图片',
          generating: '生成中...',
          generate3DModel: '生成3D模型',
          pleaseUpload: '请先上传图片',
          uploadSuccess: '上传成功',
          uploadFailed: '上传失败',
          viewLargeImage: '查看大图',
          changeImage: '更换图片',
          generating3D: '生成3D模型中...',
          modelGenerating: '3D模型生成中',
          generateFailed: '生成失败，请重试',
          generate3DFailed: '生成3D模型失败',
          share: '分享',
          report: '举报',
          help: '帮助',
          reportSuccess: '举报成功',
          helpInDev: '帮助功能开发中',
          draw1: {
            placeholder: '为模型取名',
            saveEdit: '保存编辑',
            nextStep: '下一步',
            shareModel: '分享模型',
            goPrint: '去打印',
            saveSuccess: '保存成功',
            exitConfirm: '您有未保存的操作，确定要退出吗？',
            dontSave: '不保存',
            save: '保存',
            shareFailed: '分享失败',
            saveFailed: '保存失败',
            parseImageFailed: '解析图片数据失败',
            saveFileFailed: '保存文件失败',
            notSupportShareSTL: '当前平台暂不支持分享STL'
          },
          generateConfirm: '生成确认',
          generateNewModel: '生成新模型',
          scale: '缩放',
          rotationAdjustment: '旋转调节',
          axisX: 'X轴',
          axisY: 'Y轴',
          axisZ: 'Z轴',
          reset: '重置',
          rotate90: '旋转90°',
          rotate180: '旋转180°',
          colorMarks: '颜色标记',
          area: '区域',
          addMark: '添加标记',
          remove: '删除',
          noColorMarks: '暂无颜色标记，点击添加按钮开始标记',
          selectColor: '选择颜色',
          paintingGuide: '涂色指导',
          position: '位置',
          noPaintingGuides: '暂无涂色指导，点击添加按钮开始添加',
          addPaintingGuide: '添加涂色指导',
          guideColor: '指导颜色',
          positionPlaceholder: '请输入指导位置（如：顶部、底部）',
          instructions: '指导说明',
          instructionsPlaceholder: '请输入指导说明',
          confirmAdd: '确认添加',
          fillRequiredFields: '请填写完整信息',
          unit: '个',
          modelLoadFailed: '模型加载失败',
          loading: '加载中...',
          me: '我',
          ai: 'AI',
          replying: '正在回复…',
          placeholder: '请输入你的问题',
          stop: '停止',
          send: '发送',
          featureInDev: '功能开发中',
          loadSessionFailed: '从本地存储加载 session 失败',
          saveSessionFailed: '保存 session 到本地存储失败',
          loadHistoryFailed: '加载历史会话失败',
          fetchSessionFailed: '获取 session 失败',
          chatStopped: '对话已停止',
          stopChatFailed: '停止对话接口调用失败',
          chatFailed: '对话失败，请稍后重试'
        },
        explore: {
          welcome: '欢迎来到Mixware',
          searchModel: '搜索模型',
          searchPlaceholder: '搜索你感兴趣的内容',
          dailyRecommend: '每日推荐',
          hotCreate: '热门创作',
          otherCategory: '其他类目',
          loading: '加载中...',
          releaseToRefresh: '释放立即刷新',
          pullToRefresh: '下拉刷新',
          refreshing: '正在刷新...',
          refreshComplete: '刷新完成',
          search: '搜索',
          hotSearch: '热门搜索',
          modelDetail: '模型详情',
          expand: '更多',
          collapse: '收起',
          category: '类目',
          copyright: '版权',
          printInfo: '3D模型打印信息',
          size: '尺寸',
          printTime: '打印耗时',
          showcase: '作品展示',
          noContent: '暂无内容',
          userShowcase: '用户作品展示',
          workDetail: '打印详情',
          printComplete: '打印完成',
          shareReport: '分享报告',
          share: '分享',
          advancedCreator: '高级创作者',
          description: '描述',
          printTimeLabel: '打印时间',
          material: '材料',
          sizeLabel: '尺寸',
          comments: '评论',
          like: '点赞',
          collect: '收藏',
          print: '打印',
          reply: '回复',
          submit: '提交',
          cancel: '取消',
          delete: '删除',
          viewMoreComments: '查看更多评论',
          repliesCountSuffix: '条回复',
          views: '浏览',
          sayPlaceholder: '说点什么...',
          justNow: '刚刚',
          minutesAgo: '分钟前',
          hoursAgo: '小时前',
          daysAgo: '天前',
          follow: '+ 关注',
          followed: '已关注',
          reset: '重置',
          resetSuccess: '已重置',
          center: '居中',
          rotate: '旋转',
          copy: '复制',
          fit: '适配',
          pleaseSelectModel: '请先选中模型',
          slicePreview: '模型打印预览',
          processingTips: '模型处理需要一定时间，可在',
          myPrintRecords: '我的-打印记录',
          view: '查看',
          autoPrintAfterProcess: '处理完成后会直接打印',
          cancelProcessing: '取消处理',
          confirmCancel: '确认取消',
          cancelContent: '取消后将停止模型处理，是否确认？',
          pendingTaskGenerated: '待打印任务已生成',
          printTimeAnalyzed: '打印时间已分析完成',
          modelConsumptionAnalyzed: '模型消耗克数已分析完成',
          modelDimensionsAnalyzed: '模型尺寸已分析完成',
          analysisComplete: '分析完成，请等待模型处理',
          processingComplete: '模型处理完成，准备打印',
          channelTitle: '我的频道',
          channelHint: '点击进入频道',
          createPost: '创建帖子',
          postTitlePlaceholder: '请输入帖子标题',
          postContentPlaceholder: '请分享您的3D打印作品经验...',
          addImages: '添加图片',
          maxImagesHint: '最多可上传9张图片',
          addTopicPlaceholder: '添加话题标签',
          modelIdLabel: '模型ID',
          title: '标题',
          content: '内容',
          images: '图片',
          topics: '话题',
          publishing: '发布中...',
          publishSuccess: '发布成功',
          publishFailed: '发布失败',
          publish: '发布',
          cancelCollect: '取消收藏',
          collectSuccess: '收藏成功',
          operationFailed: '操作失败',
          pause: '暂停',
          returnHome: '返回首页',
          busy: '忙碌',
          idle: '空闲',
          nozzleStatus: '喷头温度',
          currentTemp: '当前温度',
          targetTemp: '目标温度',
          progress: '进度',
          estimatedTime: '预计时间',
          printerStatus: '打印机状态',
          modelName: '模型名称',
          scale: '缩放',
          replySuccess: '回复成功',
          modelIdNotExist: '模型ID不存在',
          loadFailed: '加载失败',
          prepareDownload: '准备下载...',
          downloadStart: '下载开始',
          formatNotSupported: '格式不支持',
          formatNotSupportedMsg: '当前暂不支持 GCode 格式的模型预览，请使用 GLB、GLTF、OBJ 或 STL 格式的模型',
          startPrint: '开始打印',
          noModel: '暂无模型',
          gettingDeviceInfo: '正在获取设备信息...',
          addDeviceFirst: '请先添加设备',
          sendingPrintCommand: '正在发送打印命令...',
          printCommandSent: '打印命令已发送',
          sendPrintCommandFailed: '发送打印命令失败',
          pausePrint: '暂停打印',
          resumePrint: '恢复打印',
          restartPrint: '重新开始打印',
          pausingPrint: '正在暂停打印...',
          resumingPrint: '正在恢复打印...',
          restartingPrint: '正在重新开始打印...',
          pausePrintFailed: '暂停打印失败',
          resumePrintFailed: '恢复打印失败',
          restartPrintFailed: '重新开始打印失败'
        },
        deviceManager: {
          deviceManager: '设备管理',
          myDevices: '我的设备',
          noDevices: '暂无设备，点击下方按钮添加',
          addDevice: '添加新设备',
          scanAdd: '扫码添加',
          manualAdd: '手动添加',
          editDevice: '编辑设备',
          setDefault: '设为默认',
          setDefaultSuccess: '设置默认设备成功',
          setDefaultFailed: '设置默认设备失败',
          deleteDevice: '删除设备',
          deviceName: '设备名称',
          deviceStatus: '设备状态',
          online: '在线',
          offline: '离线',
          busy: '忙碌',
          error: '错误',
          save: '保存',
          cancel: '取消',
          confirm: '确认',
          confirmDelete: '确认删除',
          deleteConfirmContent: '确定要删除这个设备吗？',
          deleteSuccess: '删除成功',
          saveSuccess: '保存成功',
          saveFailed: '保存失败',
          // 批量操作
          batchDelete: '批量删除',
          batchDeleteConfirm: '确认批量删除',
          batchDeleteSuccess: '批量删除成功',
          batchDeleteFailed: '批量删除失败',
          selectedDevices: '已选择',
          devicesCount: '个设备',
          select: '选择',
          unnamedDevice: '未命名设备',
          parsing: '解析中...',
          invalidQrCode: '二维码无效',
          scanFailed: '扫码失败',
          pleaseSelectDevices: '请选择要删除的设备',
          confirmDeleteDevices: '确定要删除选中的',
          questionMark: '吗？',
          deleting: '删除中...',
          // 通用
          loadingFailed: '加载失败',
          deviceId: '设备ID',
          clear: '清除',
          rescan: '重新扫描',
          snCodeRequired: 'SN码不能为空',
          snCodePlaceholder: '请输入设备SN码',
          snCodeHint: 'SN码通常在设备背面或底部标签上',
          updating: '更新中...',
          // 扫码添加
          scanDevice: '扫码添加设备',
          scanQrCode: '扫描设备上的二维码或条形码',
          scanHint: '将设备SN码对准扫描框',
          startScan: '开始扫描',
          manualInput: '手动输入',
          scanResult: '扫描结果',
          snCode: 'SN码',
          deviceType: '设备类型',
          addDeviceSuccess: '设备创建成功',
          invalidSnCode: '无效的SN码',
          parseFailed: '解析失败',
          // 设备状态
          connectionStatus: '连接状态',
          printStatus: '打印状态',
          firmwareVersion: '固件版本',
          lastOnline: '最后在线',
          refreshStatus: '刷新状态',
          updateStatus: '更新状态',
          idle: '空闲',
          printing: '打印中',
          paused: '已暂停',
          completed: '已完成',
          connecting: '连接中',
          connectionError: '连接错误',
          justNow: '刚刚',
          minutesAgo: '分钟前',
          hoursAgo: '小时前',
          daysAgo: '天前',
          neverOnline: '从未在线',
          // 固件管理
          firmwareManagement: '固件管理',
          currentVersion: '当前版本',
          buildDate: '构建日期',
          firmwareStatus: '固件状态',
          unknown: '未知',
          refresh: '刷新',
          refreshing: '刷新中...',
          checkUpdate: '检查更新',
          checking: '检查中...',
          updateNow: '立即更新',
          rollback: '回滚',
          rollingBack: '回滚中...',
          updateHistory: '更新历史',
          deviceAuth: '设备认证',
          verifyAuth: '验证认证',
          verifying: '验证中...',
          refreshAuth: '刷新认证',
          refreshingAuth: '刷新中...',
          updateProgress: '更新进度',
          download: '下载',
          install: '安装',
          complete: '完成',
          normal: '正常',
          outdated: '过期',
          corrupted: '损坏',
          verified: '已验证',
          unverified: '未验证',
          expired: '已过期',
          // 设备安全
          deviceSecurity: '设备安全',
          credentialStatus: '凭证状态',
          lastAuthTime: '最后认证时间',
          verifyDevice: '验证设备',
          refreshCredential: '刷新凭证',
          resetAuth: '重置认证',
          resetting: '重置中...',
          authHistory: '认证历史',
          securityWarning: '安全警告',
          resolveNow: '立即解决',
          valid: '有效',
          invalid: '无效',
          revoked: '已撤销',
          high: '高',
          medium: '中',
          low: '低',
          verificationFailed: '验证失败',
          // 切片服务
          sliceService: '切片服务',
          sliceManagement: '切片管理',
          selectModel: '选择模型',
          pleaseSelectModel: '请选择模型',
          slicePreset: '切片预设',
          selectPreset: '选择预设',
          printMaterial: '打印材料',
          selectMaterial: '选择材料',
          startSlice: '开始切片',
          slicing: '切片中...',
          currentTask: '当前任务',
          taskId: '任务ID',
          modelName: '模型名称',
          startTime: '开始时间',
          sliceProgress: '切片进度',
          cancelTask: '取消任务',
          cancelling: '取消中...',
          previewResult: '预览结果',
          downloadGcode: '下载G代码',
          retryTask: '重试任务',
          sliceHistory: '切片历史',
          advancedSettings: '高级设置',
          layerHeight: '层高原度',
          infillDensity: '填充密度',
          printSpeed: '打印速度',
          saveSettings: '保存设置',
          goSlice: '前往切片',
          currentStage: '当前阶段',
          elapsedTime: '已用时间',
          remainingTime: '剩余时间',
          layersCount: '层数',
          pause: '暂停',
          pausing: '暂停中...',
          resume: '继续',
          resuming: '继续中...',
          sliceError: '切片错误',
          retry: '重试',
          noSliceHistory: '暂无切片历史',
          slicePresets: '切片预设',
          sliceHelp: '切片帮助',
          modelLoadFailed: '模型加载失败',
          // 模型分类
          dailyUse: '日用居家',
          toyFigure: '玩具手办',
          fashionWear: '时尚穿戴',
          digitalDevice: '数码电器',
          architecturalModel: '建筑模型',
          artCreative: '艺术创意'
        },
        settings: {
          title: '设置',
          profile: '个人资料',
          account: '账户与安全',
          language: '语言',
          logout: '退出登录',
          logoutTitle: '提示',
          logoutContent: '确定要退出登录吗？',
          logoutSuccess: '已退出登录',
          switchLanguage: '已切换为中文',
          switchLanguageEn: 'Switched to English'
        },
        tabBar: {
          explore: '探索',
          create: '创建',
          profile: '我的'
        },
        addPrinter: {
          title: '添加打印机',
          loading: '加载中...',
          noDevices: '未扫描到蓝牙设备',
          unnamedDevice: '未命名设备',
          unknownDevice: '未知设备',
          cancel: '取消',
          scanning: '扫描中...',
          noBluetoothDevices: '未扫描到任何蓝牙设备',
          bluetoothScanFailed: '蓝牙扫描失败'
        },
        profile: {
          loginRegister: '登录/注册',
          clickToLogin: '点击登录体验更多功能',
          following: '关注',
          followers: '粉丝',
          likes: '赞过',
          collections: '收藏',
          medalsWall: '勋章墙',
          newbieMedal: '新手勋章',
          creatorMedal: '创作者',
          activeUserMedal: '活跃用户',
          popularMedal: '人气王',
          modelMasterMedal: '模型大师',
          printExpertMedal: '打印达人',
          contributorMedal: '社区贡献',
          pioneerMedal: '先锋用户',
          printerPartner: '打印机伙伴',
          findPartner: '寻找伙伴',
          addPrinter: '添加打印机',
          my3DPrinter: '我的3D打印机',
          unknownModel: '未知型号',
          online: '在线',
          offline: '离线',
          unbind: '解绑',
          unbindConfirmation: '确认解绑',
          unbindContent: '确定要解绑这台打印机吗？',
          unbindSuccess: '解绑成功',
          unbindFailed: '解绑失败',
          deviceManager: '设备管理',
          emptyHint: '快去打印吧'
        },
        addDevice: {
          title: '添加设备',
          connectWifi: '连接WiFi',
          pleaseSelectWiFi: '请选择WiFi',
          scanning: '扫描中...',
          getFailedRetry: '获取失败，点击重试',
          select: '选择',
          noWiFi: '无WiFi',
          stopScan: '停止扫描',
          enterPassword: '请输入WiFi密码',
          tipsText: '请确保家庭WiFi网络为2.4G网络',
          networking: '网络连接中...',
          nextStep: '下一步',
          pleaseEnterPassword: '请输入密码'
        },
        message: {
          title: '消息',
          prompt: '提示',
          clearConfirm: '确定要清除所有消息吗？'
        },
        messageSettings: {
          title: '消息设置',
          systemNotification: '系统通知',
          pushNotification: '推送通知',
          bannerNotification: '系统中的横幅通知',
          appMessages: '应用内消息',
          messageReminder: '消息提醒',
          reminderDesc: '关闭后，将不再进行红点提示',
          printStatus: '打印状态',
          printSuccess: '打印成功',
          printFailure: '打印失败',
          goToSystemSettings: '请前往系统设置'
        },
        messageList: {
          emptyText: '暂无消息',
          cleared: '已清除所有消息'
        },
        myWorks: {
          title: '作品博物馆',
          myWorks: '我的作品',
          myLikes: '我的点赞',
          noWorks: '暂无作品',
          noLikes: '暂无点赞',
          goLike: '快去点赞吧',
          loadFailed: '加载失败',
          unknown: '未知',
          printPoster: '打印海报',
          generatingPoster: '正在生成海报...',
          posterGenerated: '海报生成成功',
          // 作品管理
          deleteWork: '删除作品',
          deleteConfirm: '确认删除',
          deleteConfirmContent: '确定要删除这个作品吗？此操作不可恢复。',
          deleteSuccess: '删除成功',
          deleteFailed: '删除失败',
          cancel: '取消',
          confirm: '确认'
        },
        printerIntro: {
          title: '打印机',
          encouragementText: '你的创造正在诞生，快去打印机旁看看吧！',
          connectionFailed: '设备连接失败，请检查网络',
          idle: '睡觉',
          printing: '工作中',
          hungry: '饿了',
          error: '生病了',
          offline: '失联了'
        },
        printerMoreIntro: {
          title: '打印机设置'
        },
        profileEdit: {
          title: '个人资料',
          save: '保存',
          saving: '保存中...',
          saveSuccess: '保存成功',
          saveFailed: '保存失败',
          avatar: '头像',
          nickname: '昵称',
          birthday: '生日',
          region: '地区',
          gender: '性别',
          notSet: '未设置',
          pleaseSelect: '请选择',
          editNickname: '修改昵称',
          enterNickname: '请输入昵称',
          chooseFromAlbum: '从相册选择',
          takePhoto: '拍照',
          beijing: '北京市',
          shanghai: '上海市',
          guangzhou: '广州市',
          shenzhen: '深圳市',
          hangzhou: '杭州市',
          nanjing: '南京市',
          other: '其他',
          male: '男',
          female: '女',
          private: '保密',
          uploadSuccessNoUrl: '上传成功但未返回URL',
          uploadAvatarFailed: '上传头像失败'
        },
        accountSecurity: {
          title: '账户与安全',
          resetPasswordLabel: '重置密码',
          emailBinding: {
            title: '邮箱绑定',
            emailLabel: '邮箱',
            emailPlaceholder: '请输入邮箱地址',
            codeLabel: '验证码',
            codePlaceholder: '请输入验证码',
            getCode: '获取验证码',
            submitButton: '确认绑定',
            enterEmail: '请输入邮箱地址',
            codeSent: '验证码已发送',
            fillAllFields: '请填写完整信息',
            bindSuccess: '邮箱绑定成功',
            bindFailed: '邮箱绑定失败',
            codeSendFailed: '验证码发送失败',
            binding: '绑定中...',
            boundEmail: '已绑定邮箱',
            changeEmail: '更改邮箱'
          },
          thirdPartyBindingLabel: '第三方账号绑定',
          thirdPartyBinding: {
            title: '第三方账号绑定',
            googleBinding: 'Google绑定',
            bound: '已绑定',
            unbound: '未绑定',
            bind: '绑定',
            unbind: '解绑',
            binding: '绑定中...',
            bindingSuccess: '绑定成功',
            confirmCancel: '解绑确认',
            confirmCancelContent: '确定要解绑Google账号吗？',
            unbindSuccess: '解绑成功'
          },
          deleteAccount: '注销账号',
          deleteAccountTitle: '注销账号',
          deleteAccountContent: '注销账号后，您的所有数据将被永久删除，无法恢复。确定要继续吗？',
          confirm: '确定',
          cancel: '取消',
          deleting: '正在删除...',
          deleteSuccess: '账号已注销',
          deleteFailed: '注销失败',
          resetPassword: {
            title: '重置密码',
            emailLabel: '邮箱',
            emailPlaceholder: '请输入邮箱',
            codeLabel: '验证码',
            codePlaceholder: '请输入验证码',
            oldPasswordLabel: '旧密码',
            oldPasswordPlaceholder: '请输入旧密码',
            newPasswordLabel: '新密码',
            newPasswordPlaceholder: '请输入新密码',
            confirmPasswordLabel: '确认密码',
            confirmPasswordPlaceholder: '请确认新密码',
            getCode: '获取验证码',
            resetButton: '重置密码',
            enterEmail: '请输入邮箱',
            codeSent: '验证码已发送',
            fillAllFields: '请填写完整信息',
            enterCode: '请输入验证码',
            enterNewPassword: '请输入新密码',
            passwordsNotMatch: '两次密码输入不一致',
            newPasswordSameAsOld: '新密码不能与旧密码相同',
            resetSuccess: '密码重置成功',
            resetFailed: '密码重置失败',
            sending: '发送中...',
            sendFailed: '发送失败',
            resetting: '重置中...',
            passwordTooShort: '密码长度不能少于6位'
          }
        },
        deviceSuccess: {
          title: '设备添加',
          bindingSuccess: '设备绑定成功',
          openExperience: '开启3D打印体验！',
          goHome: '返回个人主页',
          bindingSuccessToast: '绑定成功',
          bindingFailed: '绑定失败'
        },
        medalDetail: {
          medalsWall: '勋章墙',
          achieved: '已达成',
          notAchieved: '未达成',
          achievementStandard: '达成标准：',
          newbieMedal: '新手勋章',
          newbieMedalDesc: '首次登录并完成设备绑定',
          creatorMedal: '创作者',
          creatorMedalDesc: '创建并发布3个模型作品',
          activeUserMedal: '活跃用户',
          activeUserMedalDesc: '连续7天登录应用',
          popularMedal: '人气王',
          popularMedalDesc: '作品获得50次点赞或收藏',
          modelMasterMedal: '模型大师',
          modelMasterMedalDesc: '创建并发布10个模型作品',
          printExpertMedal: '打印达人',
          printExpertMedalDesc: '完成5次3D打印任务',
          contributorMedal: '社区贡献',
          contributorMedalDesc: '发表20条评论或分享10次作品',
          pioneerMedal: '先锋用户',
          pioneerMedalDesc: '注册时间在应用上线前30天内',
          sliceSettings: '切片设置',
          layerHeight: '层高',
          infillDensity: '填充密度',
          printSpeed: '打印速度',
          startSlice: '开始切片',
          slicing: '切片中',
          sliceSuccess: '切片成功',
          sliceFailed: '切片失败',
          readyToPrint: '准备打印'
        },
        myFavorites: {
          title: '收藏',
          emptyText: '暂无收藏',
          noFavorites: '暂无收藏内容',
          daysAgo: '天前',
          hoursAgo: '小时前',
          minutesAgo: '分钟前',
          justNow: '刚刚'
        },
        myLikes: {
          title: '赞过',
          emptyText: '暂无赞过的内容',
          noLikedContent: '暂无点赞内容'
        },
        loginUserAgreement: {
          title: '用户协议',
          section1Title: '1. 服务条款',
          section1Content: '欢迎使用 mixware 服务。在使用本服务前，请仔细阅读并理解本用户协议。使用本服务即表示您同意本协议的所有条款。',
          section2Title: '2. 用户注册',
          section2Content: '用户在注册时必须提供真实准确的个人信息。用户有责任维护其账户和密码的保密性，并对该账户下发生的所有活动负责。',
          section3Title: '3. 服务使用',
          section3Content: '用户承诺不将本服务用于任何非法或不当活动，包括但不限于发布非法信息、侵犯他人知识产权等。',
          section4Title: '4. 隐私保护',
          section4Content: '我们将采取合理的技术措施保护用户个人信息的安全，但不对因不可抗力或第三方原因导致的信息泄露承担责任。',
          section5Title: '5. 免责声明',
          section5Content: '本服务按"原样"提供，不保证连续性、及时性、安全性或无错误。用户使用本服务所产生的风险由用户自行承担。',
          section6Title: '6. 协议修改',
          section6Content: '我们保留随时修改本协议的权利。修改后的协议自发布之日起生效。如用户不同意修改后的协议，应停止使用本服务。',
          section7Title: '7. 适用法律',
          section7Content: '本协议的订立、执行和解释均适用中华人民共和国法律。如发生争议，双方应通过友好协商解决。'
        },
        commentList: {
          title: '全部评论',
          comments: '条评论',
          sortByTime: '按时间排序',
          sortByLikes: '按点赞数排序',
          sortByReplies: '按回复数排序',
          reply: '回复',
          delete: '删除',
          replyTo: '回复',
          placeholder: '说点什么...',
          inputPlaceholder: '写点什么吧...',
          publish: '发布',
          deleteConfirm: '确认删除',
          deleteContent: '确定要删除这条评论吗？',
          deleteSuccess: '删除成功',
          deleteFailed: '删除失败',
          publishSuccess: '发布成功',
          publishFailed: '发布失败',
          justNow: '刚刚',
          minutesAgo: '分钟前',
          hoursAgo: '小时前',
          daysAgo: '天前',
          imageUploadInDev: '图片上传功能开发中'
        },
        followList: {
          title: '关注列表',
          followingTitle: '关注列表',
          followersTitle: '粉丝列表',
          following: '关注',
          followers: '粉丝',
          follow: '+ 关注',
          followed: '已关注',
          mutualFollow: '互相关注',
          noFollowing: '还没有关注任何人',
          noFollowers: '还没有粉丝',
          noDescription: '这个人很懒，什么都没写',
          followSuccess: '关注成功',
          unfollowSuccess: '取消关注',
          operationFailed: '操作失败'
        },
        loginMixwareAgreement: {
          title: 'mixware用户协议',
          section1Title: '1. mixware服务说明',
          section1Content: 'mixware是一款专业的3D打印管理应用，为用户提供模型浏览、创作、打印管理等全面服务。本协议是您与mixware之间关于使用本服务的法律协议。',
          section2Title: '2. 账号管理',
          section2Content: '用户在mixware注册的账号归用户所有，但mixware保留管理账号的权利。用户不得转让、出售或出借账号。如发现账号被盗，应立即通知mixware。',
          section3Title: '3. 3D模型版权',
          section3Content: 'mixware平台上的3D模型版权归原作者所有。用户可以浏览、下载和使用模型，但不得用于商业目的或侵犯原作者的权益。用户上传的模型应确保拥有合法的版权。',
          section4Title: '4. 3D打印机设备管理',
          section4Content: '用户可以通过mixware管理连接的3D打印机设备。用户应确保设备使用符合当地法律法规，不得用于打印违禁物品。mixware不对因设备使用不当造成的损失负责。',
          section5Title: '5. 服务费用',
          section5Content: 'mixware的基础服务免费提供，但某些高级功能可能需要付费。付费服务的价格和条款以mixware官方公告为准。购买付费服务后不支持退款。',
          section6Title: '6. 用户行为规范',
          section6Content: '用户在使用mixware服务时应遵守以下规范：不得发布违法、有害、色情或暴力内容；不得侵犯他人的知识产权；不得干扰或破坏正常的服务运行；不得利用服务进行欺诈或其他违法活动。',
          section7Title: '7. 知识产权',
          section7Content: 'mixware平台上的所有内容，包括但不限于软件、设计、文本、图片、视频等，均受知识产权法保护。未经mixware书面许可，用户不得复制、分发、修改或用于商业目的。',
          section8Title: '8. 免责声明',
          section8Content: 'mixware对以下情况不承担责任：因用户操作不当导致的打印失败；因设备故障或网络问题导致的服务中断；第三方内容或服务的质量问题；不可抗力事件。',
          section9Title: '9. 服务终止',
          section9Content: 'mixware有权在以下情况下终止或暂停服务：用户违反本协议；用户行为损害mixware或其他用户的利益；法律要求或其他必要情况。服务终止后，用户账号将被冻结或删除。',
          section10Title: '10. 争议解决',
          section10Content: '因本协议产生的任何争议，应首先通过友好协商解决。协商不成的，任何一方均可向mixware所在地的人民法院提起诉讼。',
          section11Title: '11. 联系方式',
          section11Content: '如果您对本协议有任何疑问或建议，请通过以下方式联系我们：邮箱：support@mixware.com；电话：400-XXX-XXXX。'
        },
        loginPrivacy: {
          title: '隐私通知',
          section1Title: '1. 信息收集',
          section1Content: '我们可能会收集您的个人信息，包括但不限于：电子邮件地址、设备信息、使用日志等。这些信息用于提供和改进我们的服务。',
          section2Title: '2. 信息使用',
          section2Content: '我们使用收集的信息来：提供、维护和改进我们的服务；处理您的请求和交易；向您发送相关通知；保护我们的服务和用户。',
          section3Title: '3. 信息共享',
          section3Content: '除非获得您的明确同意或法律要求，否则我们不会出售、交易或转让您的个人信息给第三方。我们可能与受信任的第三方服务提供商共享必要信息以提供服务。',
          section4Title: '4. 信息安全',
          section4Content: '我们采取合理的技术和管理措施来保护您的个人信息安全，包括数据加密、访问控制、安全审计等。但请注意，没有任何互联网传输或存储方法是100%安全的。',
          section5Title: '5. Cookie使用',
          section5Content: '我们使用Cookie和类似技术来改善用户体验、分析使用情况、提供个性化内容。您可以通过浏览器设置管理Cookie偏好。',
          section6Title: '6. 您的权利',
          section6Content: '您有权访问、更正、删除您的个人信息，以及反对或限制某些处理。您可以通过联系我们行使这些权利。',
          section7Title: '7. 儿童隐私',
          section7Content: '我们的服务不针对13岁以下的儿童。我们不会故意收集13岁以下儿童的个人信息。如果发现此类情况，我们将立即删除。',
          section8Title: '8. 隐私政策更新',
          section8Content: '我们可能会不时更新此隐私政策。更新的政策将在此页面上发布，并注明修订日期。重大变更将通过其他方式通知您。'
        }
      }
      
      const en = {
        login: {
          title: 'Login',
          accountName: 'mixware Account',
          loginTab: 'Login',
          loginByCodeTab: 'Code Login',
          passwordLoginTab: 'Password Login',
          registerTab: 'Register',
          usernameLabel: 'Username',
          usernamePlaceholder: 'Please enter username',
          emailLabel: 'Email',
          emailPlaceholder: 'Please enter email address',
          codeLabel: 'Verification Code',
          codePlaceholder: 'Please enter verification code',
          getCode: 'Get Code',
          passwordLabel: 'Password',
          passwordPlaceholder: 'Please enter password',
          confirmPasswordLabel: 'Confirm Password',
          confirmPasswordPlaceholder: 'Please enter password again',
          birthdayLabel: 'Birthday',
          birthdayPlaceholder: 'Please select birthday',
          marketingConsent: 'Agree to receive marketing information',
          loginButton: 'Login',
          registerButton: 'Register',
          forgetPassword: 'Forgot Password',
          noAccount: 'No account yet?',
          registerNow: 'Register now',
          enterEmail: 'Please enter email',
          enterPassword: 'Please enter password',
          enterUsername: 'Please fill in username',
          enterCode: 'Please fill in verification code',
          confirmPassword: 'Please confirm password',
          passwordsNotMatch: 'Passwords do not match',
          agreeToTerms: 'Please read and agree to the user agreement first',
          loginSuccess: 'Login successful',
          loginFailed: 'Login failed',
          registerSuccess: 'Registration successful',
          registerFailed: 'Registration failed',
          emailExists: 'Email already exists',
          codeError: 'Invalid verification code',
          codeExpired: 'Verification code expired',
          sendCodeFailed: 'Failed to send verification code',
          thirdPartyLogin: 'Third-party Login',
          googleLogin: 'Google Login',
          googleLoginFailed: 'Google login failed',
          readAndAgree: 'I have read',
          userAgreement: 'User Agreement',
          privacyNotice: 'Privacy Notice',
          mixwareAgreement: 'mixware User Agreement'
        },
        create: {
          title: 'Create',
          allFunction: 'All Functions',
          allDesc: 'Experience all creative tools',
          photography: 'Photography',
          photographyDesc: 'Generate 3D models by photo',
          chat: 'Chat',
          chatDesc: 'Generate 3D models by chat',
          textToModel: 'Text to Model',
          promptPlaceholder: 'Enter description, e.g., A cute little cat',
          pleaseInputPrompt: 'Please enter description',
          aiChat: 'AI Chat',
          aiChatDesc: 'Intelligent AI assistant',
          aiChatPlaceholder: 'AI chat feature under development',
          draw: 'Draw',
          drawDesc: 'Generate 3D models by drawing',
          uploadModel: 'Upload Model',
          transform: 'Transform',
          transformDesc: 'Generate models by adjusting parameters',
          mainView: 'Main View',
          clickUpload: 'Click to upload main view',
          clickChangeImage: 'Click to change image',
          generating: 'Generating...',
          generate3DModel: 'Generate 3D Model',
          pleaseUpload: 'Please upload image first',
          uploadSuccess: 'Upload successful',
          uploadFailed: 'Upload failed',
          viewLargeImage: 'View large image',
          changeImage: 'Change image',
          generating3D: 'Generating 3D model...',
          modelGenerating: '3D model generating',
          generateFailed: 'Generation failed, please try again',
          generate3DFailed: 'Failed to generate 3D model',
          share: 'Share',
          report: 'Report',
          help: 'Help',
          reportSuccess: 'Report successful',
          helpInDev: 'Help feature under development',
          draw1: {
            placeholder: 'Name your model',
            saveEdit: 'Save Edit',
            nextStep: 'Next Step',
            shareModel: 'Share Model',
            goPrint: 'Go Print',
            saveSuccess: 'Save Successful',
            exitConfirm: 'You have unsaved changes, are you sure to exit?',
            dontSave: 'Don\'t Save',
            save: 'Save',
            shareFailed: 'Share Failed',
            saveFailed: 'Save Failed',
            parseImageFailed: 'Failed to parse image data',
            saveFileFailed: 'Failed to save file',
            notSupportShareSTL: 'Sharing STL is not supported on this platform'
          },
          generateConfirm: 'Generate Confirmation',
          generateNewModel: 'Generate new model',
          scale: 'Scale',
          rotationAdjustment: 'Rotation Adjustment',
          axisX: 'X-axis',
          axisY: 'Y-axis',
          axisZ: 'Z-axis',
          reset: 'Reset',
          rotate90: 'Rotate 90°',
          rotate180: 'Rotate 180°',
          colorMarks: 'Color marks',
          area: 'Area',
          addMark: 'Add Mark',
          remove: 'Remove',
          noColorMarks: 'No color marks, click add button to start marking',
          selectColor: 'Select Color',
          paintingGuide: 'Painting guide',
          position: 'Position',
          noPaintingGuides: 'No painting guides, click add button to start adding',
          addPaintingGuide: 'Add Painting Guide',
          guideColor: 'Guide Color',
          positionPlaceholder: 'Please enter guide position (e.g., top, bottom)',
          instructions: 'Instructions',
          instructionsPlaceholder: 'Please enter instructions',
          confirmAdd: 'Confirm Add',
          fillRequiredFields: 'Please fill in all required fields',
          unit: 'piece',
          modelLoadFailed: 'Model load failed',
          loading: 'Loading...',
          me: 'Me',
          ai: 'AI',
          replying: 'Replying...',
          placeholder: 'Enter your question',
          stop: 'Stop',
          send: 'Send',
          featureInDev: 'Feature under development',
          loadSessionFailed: 'Failed to load session from local storage',
          saveSessionFailed: 'Failed to save session to local storage',
          loadHistoryFailed: 'Failed to load chat history',
          fetchSessionFailed: 'Failed to fetch session',
          chatStopped: 'Chat stopped',
          stopChatFailed: 'Failed to call stop chat API',
          chatFailed: 'Chat failed, please try again later'
        },
        explore: {
          welcome: 'Welcome to Mixware',
          searchModel: 'Search Model',
          searchPlaceholder: 'Search for what you are interested in',
          dailyRecommend: 'Daily',
          hotCreate: 'Hot',
          otherCategory: 'Categories',
          loading: 'Loading...',
          releaseToRefresh: 'Release to refresh',
          pullToRefresh: 'Pull to refresh',
          refreshing: 'Refreshing...',
          refreshComplete: 'Refresh complete',
          search: 'Search',
          hotSearch: 'Hot Search',
          modelDetail: 'Model Detail',
          expand: 'More',
          collapse: 'Collapse',
          category: 'Category',
          copyright: 'Copyright',
          printInfo: '3D Model Printing Information',
          size: 'Size',
          printTime: 'Printing Time',
          showcase: 'Showcase',
          noContent: 'No content',
          userShowcase: 'User Showcase',
          workDetail: 'Print Detail',
          printComplete: 'Print Complete',
          shareReport: 'Share Report',
          share: 'Share',
          advancedCreator: 'Advanced Creator',
          description: 'Description',
          printTimeLabel: 'Print Time',
          material: 'Material',
          sizeLabel: 'Size',
          comments: 'Comments',
          like: 'Like',
          collect: 'Collect',
          print: 'Print',
          reply: 'Reply',
          submit: 'Submit',
          cancel: 'Cancel',
          delete: 'Delete',
          viewMoreComments: 'View More Comments',
          views: 'views',
          sayPlaceholder: 'Say something...',
          justNow: 'Just now',
          minutesAgo: ' minutes ago',
          hoursAgo: ' hours ago',
          daysAgo: ' days ago',
          follow: '+ Follow',
          followed: 'Followed',
          reset: 'Reset',
          resetSuccess: 'Reset',
          center: 'Center',
          rotate: 'Rotate',
          copy: 'Copy',
          fit: 'Fit',
          pleaseSelectModel: 'Please select model first',
          slicePreview: 'Model Print Preview',
          processingTips: 'Model processing takes time, you can check in',
          myPrintRecords: 'My-Print Records',
          view: 'view',
          autoPrintAfterProcess: 'Will print directly after processing',
          cancelProcessing: 'Cancel Processing',
          confirmCancel: 'Confirm Cancel',
          cancelContent: 'Canceling will stop model processing, confirm?',
          pendingTaskGenerated: 'Pending print task generated',
          printTimeAnalyzed: 'Print time analysis complete',
          modelConsumptionAnalyzed: 'Model consumption analysis complete',
          modelDimensionsAnalyzed: 'Model dimensions analysis complete',
          analysisComplete: 'Analysis complete, waiting for model processing',
          processingComplete: 'Model processing complete, preparing to print',
          channelTitle: 'My Channels',
          channelHint: 'Tap to enter channel',
          createPost: 'Create Post',
          postTitlePlaceholder: 'Enter post title',
          postContentPlaceholder: 'Share your 3D printing experience...',
          addImages: 'Add Images',
          maxImagesHint: 'Up to 9 images',
          addTopicPlaceholder: 'Add topic tags',
          modelIdLabel: 'Model ID',
          title: 'Title',
          content: 'Content',
          images: 'Images',
          topics: 'Topics',
          publishing: 'Publishing...',
          publishSuccess: 'Published successfully',
          publishFailed: 'Failed to publish',
          publish: 'Publish',
          cancelCollect: 'Cancel Collection',
          collectSuccess: 'Collection successful',
          operationFailed: 'Operation failed',
          pause: 'Pause',
          returnHome: 'Return Home',
          busy: 'Busy',
          idle: 'Idle',
          nozzleStatus: 'Nozzle Temperature',
          currentTemp: 'Current Temperature',
          targetTemp: 'Target Temperature',
          progress: 'Progress',
          estimatedTime: 'Estimated Time',
          printerStatus: 'Printer Status',
          modelName: 'Model Name',
          scale: 'Scale',
          replySuccess: 'Reply successful',
          modelIdNotExist: 'Model ID does not exist',
          loadFailed: 'Load failed',
          prepareDownload: 'Preparing download...',
          downloadStart: 'Download started',
          formatNotSupported: 'Format not supported',
          formatNotSupportedMsg: 'GCode format model preview is currently not supported. Please use GLB, GLTF, OBJ, or STL format models',
          startPrint: 'Start Print',
          noModel: 'No model available',
          gettingDeviceInfo: 'Getting device info...',
          addDeviceFirst: 'Please add device first',
          sendingPrintCommand: 'Sending print command...',
          printCommandSent: 'Print command sent',
          sendPrintCommandFailed: 'Failed to send print command',
          pausePrint: 'Pause Print',
          resumePrint: 'Resume Print',
          restartPrint: 'Restart Print',
          pausingPrint: 'Pausing print...',
          resumingPrint: 'Resuming print...',
          restartingPrint: 'Restarting print...',
          pausePrintFailed: 'Failed to pause print',
          resumePrintFailed: 'Failed to resume print',
          restartPrintFailed: 'Failed to restart print'
        },
        deviceManager: {
          deviceManager: 'Device Manager',
          myDevices: 'My Devices',
          noDevices: 'No devices, click button below to add',
          addDevice: 'Add New Device',
          scanAdd: 'Scan to Add',
          manualAdd: 'Manual Add',
          editDevice: 'Edit Device',
          setDefault: 'Set as Default',
          setDefaultSuccess: 'Set default device successful',
          setDefaultFailed: 'Set default device failed',
          deleteDevice: 'Delete Device',
          deviceName: 'Device Name',
          deviceStatus: 'Device Status',
          online: 'Online',
          offline: 'Offline',
          busy: 'Busy',
          error: 'Error',
          save: 'Save',
          cancel: 'Cancel',
          confirm: 'Confirm',
          confirmDelete: 'Confirm Delete',
          deleteConfirmContent: 'Are you sure you want to delete this device?',
          deleteSuccess: 'Delete successful',
          saveSuccess: 'Save successful',
          saveFailed: 'Save failed',
          // Batch Operations
          batchDelete: 'Batch Delete',
          batchDeleteConfirm: 'Confirm Batch Delete',
          batchDeleteSuccess: 'Batch delete successful',
          batchDeleteFailed: 'Batch delete failed',
          selectedDevices: 'Selected',
          devicesCount: 'devices',
          select: 'Select',
          unnamedDevice: 'Unnamed Device',
          parsing: 'Parsing...',
          invalidQrCode: 'Invalid QR Code',
          scanFailed: 'Scan failed',
          pleaseSelectDevices: 'Please select devices to delete',
          confirmDeleteDevices: 'Confirm deletion of selected',
          questionMark: '?',
          deleting: 'Deleting...',
          // Common
          loadingFailed: 'Loading failed',
          deviceId: 'Device ID',
          clear: 'Clear',
          rescan: 'Rescan',
          snCodeRequired: 'SN code cannot be empty',
          snCodePlaceholder: 'Please enter device SN code',
          snCodeHint: 'SN code is usually on the back or bottom label of the device',
          updating: 'Updating...',
          // Scan to Add
          scanDevice: 'Scan Device',
          scanQrCode: 'Scan QR code or barcode on device',
          scanHint: 'Align device SN code with scan frame',
          startScan: 'Start Scan',
          manualInput: 'Manual Input',
          scanResult: 'Scan Result',
          snCode: 'SN Code',
          deviceType: 'Device Type',
          addDeviceSuccess: 'Device created successfully',
          invalidSnCode: 'Invalid SN code',
          parseFailed: 'Parse failed',
          // Device Status
          connectionStatus: 'Connection Status',
          printStatus: 'Print Status',
          firmwareVersion: 'Firmware Version',
          lastOnline: 'Last Online',
          refreshStatus: 'Refresh Status',
          updateStatus: 'Update Status',
          idle: 'Idle',
          printing: 'Printing',
          paused: 'Paused',
          completed: 'Completed',
          connecting: 'Connecting',
          connectionError: 'Connection Error',
          justNow: 'Just now',
          minutesAgo: 'minutes ago',
          hoursAgo: 'hours ago',
          daysAgo: 'days ago',
          neverOnline: 'Never online',
          // Firmware Management
          firmwareManagement: 'Firmware Management',
          currentVersion: 'Current Version',
          buildDate: 'Build Date',
          firmwareStatus: 'Firmware Status',
          unknown: 'Unknown',
          refresh: 'Refresh',
          refreshing: 'Refreshing...',
          checkUpdate: 'Check Update',
          checking: 'Checking...',
          updateNow: 'Update Now',
          rollback: 'Rollback',
          rollingBack: 'Rolling back...',
          updateHistory: 'Update History',
          deviceAuth: 'Device Auth',
          verifyAuth: 'Verify Auth',
          verifying: 'Verifying...',
          refreshAuth: 'Refresh Auth',
          refreshingAuth: 'Refreshing...',
          updateProgress: 'Update Progress',
          download: 'Download',
          install: 'Install',
          complete: 'Complete',
          normal: 'Normal',
          outdated: 'Outdated',
          corrupted: 'Corrupted',
          verified: 'Verified',
          unverified: 'Unverified',
          expired: 'Expired',
          // Device Security
          deviceSecurity: 'Device Security',
          credentialStatus: 'Credential Status',
          lastAuthTime: 'Last Auth Time',
          verifyDevice: 'Verify Device',
          refreshCredential: 'Refresh Credential',
          resetAuth: 'Reset Auth',
          resetting: 'Resetting...',
          authHistory: 'Auth History',
          securityWarning: 'Security Warning',
          resolveNow: 'Resolve Now',
          valid: 'Valid',
          invalid: 'Invalid',
          revoked: 'Revoked',
          high: 'High',
          medium: 'Medium',
          low: 'Low',
          verificationFailed: 'Verification Failed',
          // Slice Service
          sliceService: 'Slice Service',
          sliceManagement: 'Slice Management',
          selectModel: 'Select Model',
          pleaseSelectModel: 'Please select model',
          slicePreset: 'Slice Preset',
          selectPreset: 'Select preset',
          printMaterial: 'Print Material',
          selectMaterial: 'Select material',
          startSlice: 'Start Slice',
          slicing: 'Slicing...',
          currentTask: 'Current Task',
          taskId: 'Task ID',
          modelName: 'Model Name',
          startTime: 'Start Time',
          sliceProgress: 'Slice Progress',
          cancelTask: 'Cancel Task',
          cancelling: 'Cancelling...',
          previewResult: 'Preview Result',
          downloadGcode: 'Download G-code',
          retryTask: 'Retry Task',
          sliceHistory: 'Slice History',
          advancedSettings: 'Advanced Settings',
          layerHeight: 'Layer Height',
          infillDensity: 'Infill Density',
          printSpeed: 'Print Speed',
          saveSettings: 'Save Settings',
          goSlice: 'Go Slice',
          currentStage: 'Current Stage',
          elapsedTime: 'Elapsed Time',
          remainingTime: 'Remaining Time',
          layersCount: 'Layers',
          pause: 'Pause',
          pausing: 'Pausing...',
          resume: 'Resume',
          resuming: 'Resuming...',
          sliceError: 'Slice Error',
          retry: 'Retry',
          noSliceHistory: 'No slice history',
          slicePresets: 'Slice Presets',
          sliceHelp: 'Slice Help',
          modelLoadFailed: 'Model load failed',
          // Model categories
          dailyUse: 'Daily Use & Home',
          toyFigure: 'Toys & Collectibles',
          fashionWear: 'Fashion & Wearables',
          digitalDevice: 'Digital & Electronics',
          architecturalModel: 'Architectural Models',
          artCreative: 'Art & Creative'
        },
        settings: {
          title: 'Settings',
          profile: 'Profile',
          account: 'Account & Security',
          language: 'Language',
          logout: 'Logout',
          logoutTitle: 'Notice',
          logoutContent: 'Are you sure to log out?',
          logoutSuccess: 'Logged out',
          switchLanguage: 'Switched to Chinese',
          switchLanguageEn: 'Switched to English'
        },
        tabBar: {
          explore: 'Explore',
          create: 'Create',
          profile: 'Profile'
        },
        addPrinter: {
          title: 'Add Printer',
          loading: 'Loading...',
          noDevices: 'No Bluetooth devices found',
          unnamedDevice: 'Unnamed Device',
          unknownDevice: 'Unknown Device',
          cancel: 'Cancel',
          scanning: 'Scanning...',
          noBluetoothDevices: 'No Bluetooth devices scanned',
          bluetoothScanFailed: 'Bluetooth scan failed'
        },
        profile: {
          loginRegister: 'Login/Register',
          clickToLogin: 'Click to login and experience more features',
          following: 'Following',
          followers: 'Followers',
          likes: 'Likes',
          collections: 'Collections',
          medalsWall: 'Medals Wall',
          newbieMedal: 'Newbie Medal',
          creatorMedal: 'Creator',
          activeUserMedal: 'Active User',
          popularMedal: 'Popular King',
          modelMasterMedal: 'Model Master',
          printExpertMedal: 'Print Expert',
          contributorMedal: 'Community Contributor',
          pioneerMedal: 'Pioneer User',
          myWorks: 'My Works Museum',
          printerPartner: 'Printer Partner',
          findPartner: 'Find Partner',
          addPrinter: 'Add Printer',
          my3DPrinter: 'My 3D Printer',
          unknownModel: 'Unknown Model',
          online: 'Online',
          offline: 'Offline',
          unbind: 'Unbind',
          unbindConfirmation: 'Confirm Unbind',
          unbindContent: 'Are you sure you want to unbind this printer?',
          unbindSuccess: 'Unbind Successful',
          unbindFailed: 'Unbind Failed',
          deviceManager: 'Device Manager',
          emptyHint: 'Go print now'
        },
        medalDetail: {
          medalsWall: 'Medals Wall',
          achieved: 'Achieved',
          notAchieved: 'Not Achieved',
          achievementStandard: 'Achievement Standard: ',
          newbieMedal: 'Newbie Medal',
          newbieMedalDesc: 'First login and complete device binding',
          creatorMedal: 'Creator',
          creatorMedalDesc: 'Create and publish 3 model works',
          activeUserMedal: 'Active User',
          activeUserMedalDesc: 'Login continuously for 7 days',
          popularMedal: 'Popular King',
          popularMedalDesc: 'Works receive 50 likes or favorites',
          modelMasterMedal: 'Model Master',
          modelMasterMedalDesc: 'Create and publish 10 model works',
          printExpertMedal: 'Print Expert',
          printExpertMedalDesc: 'Complete 5 3D printing tasks',
          contributorMedal: 'Community Contributor',
          contributorMedalDesc: 'Post 20 comments or share 10 works',
          pioneerMedal: 'Pioneer User',
          pioneerMedalDesc: 'Registered within 30 days before app launch',
          sliceSettings: 'Slice Settings',
          layerHeight: 'Layer Height',
          infillDensity: 'Infill Density',
          printSpeed: 'Print Speed',
          startSlice: 'Start Slice',
          slicing: 'Slicing',
          sliceSuccess: 'Slice Success',
          sliceFailed: 'Slice Failed',
          readyToPrint: 'Ready to Print'
        },
        myFavorites: {
          title: 'My Favorites',
          emptyText: 'No favorites yet',
          noFavorites: 'No favorite content',
          daysAgo: ' days ago',
          hoursAgo: ' hours ago',
          minutesAgo: ' minutes ago',
          justNow: 'Just now'
        },
        myLikes: {
          title: 'My Likes',
          emptyText: 'No liked content yet',
          noLikedContent: 'No liked content'
        },
        myWorks: {
          title: 'My Works Museum',
          myWorks: 'My Works',
          myLikes: 'My Likes',
          noWorks: 'No works yet',
          noLikes: 'No likes',
          goLike: 'Go like some works',
          loadFailed: 'Load Failed',
          unknown: 'Unknown',
          printPoster: 'Print Poster',
          generatingPoster: 'Generating poster...',
          posterGenerated: 'Poster generated successfully',
          // 作品管理
          deleteWork: 'Delete Work',
          deleteConfirm: 'Confirm Delete',
          deleteConfirmContent: 'Are you sure you want to delete this work? This action cannot be undone.',
          deleteSuccess: 'Delete successful',
          deleteFailed: 'Delete failed',
          cancel: 'Cancel',
          confirm: 'Confirm',
          emptyHint: 'Go print now'
        },
        profileEdit: {
          title: 'Profile',
          save: 'Save',
          saving: 'Saving...',
          saveSuccess: 'Saved Successfully',
          saveFailed: 'Save Failed',
          avatar: 'Avatar',
          nickname: 'Nickname',
          birthday: 'Birthday',
          region: 'Region',
          gender: 'Gender',
          notSet: 'Not Set',
          pleaseSelect: 'Please Select',
          editNickname: 'Edit Nickname',
          enterNickname: 'Please Enter Nickname',
          chooseFromAlbum: 'Choose from Album',
          takePhoto: 'Take Photo',
          beijing: 'Beijing',
          shanghai: 'Shanghai',
          guangzhou: 'Guangzhou',
          shenzhen: 'Shenzhen',
          hangzhou: 'Hangzhou',
          nanjing: 'Nanjing',
          other: 'Other',
          male: 'Male',
          female: 'Female',
          private: 'Private',
          uploadSuccessNoUrl: 'Upload Success But No URL Returned',
          uploadAvatarFailed: 'Upload Avatar Failed'
        },
        accountSecurity: {
          title: 'Account & Security',
          resetPasswordLabel: 'Reset Password',
          emailBinding: {
            title: 'Email Binding',
            emailLabel: 'Email',
            emailPlaceholder: 'Please enter email address',
            codeLabel: 'Verification Code',
            codePlaceholder: 'Please enter verification code',
            getCode: 'Get Code',
            submitButton: 'Confirm Binding',
            enterEmail: 'Please enter email address',
            codeSent: 'Verification code sent',
            fillAllFields: 'Please fill in all information',
            bindSuccess: 'Email binding successful',
            bindFailed: 'Email binding failed',
            codeSendFailed: 'Failed to send verification code',
            binding: 'Binding...',
            boundEmail: 'Bound Email',
            changeEmail: 'Change Email'
          },
          thirdPartyBindingLabel: 'Third-party Binding',
          thirdPartyBinding: {
            title: 'Third-party Account Binding',
            googleBinding: 'Google Binding',
            bound: 'Bound',
            unbound: 'Not bound',
            bind: 'Bind',
            unbind: 'Unbind',
            binding: 'Binding...',
            bindingSuccess: 'Binding successful',
            confirmCancel: 'Unbind Confirmation',
            confirmCancelContent: 'Are you sure you want to unbind the Google account?',
            unbindSuccess: 'Unbind successful'
          },
          resetPassword: {
            title: 'Reset Password',
            emailLabel: 'Email',
            emailPlaceholder: 'Please enter email',
            codeLabel: 'Verification Code',
            codePlaceholder: 'Please enter verification code',
            oldPasswordLabel: 'Old Password',
            oldPasswordPlaceholder: 'Please enter old password',
            newPasswordLabel: 'New Password',
            newPasswordPlaceholder: 'Please enter new password',
            confirmPasswordLabel: 'Confirm Password',
            confirmPasswordPlaceholder: 'Please confirm new password',
            getCode: 'Get Code',
            resetButton: 'Reset Password',
            enterEmail: 'Please enter email',
            codeSent: 'Verification code sent',
            fillAllFields: 'Please fill in all information',
            enterCode: 'Please enter verification code',
            enterNewPassword: 'Please enter new password',
            passwordsNotMatch: 'Passwords do not match',
            newPasswordSameAsOld: 'New password cannot be the same as old password',
            resetSuccess: 'Password reset successful',
            resetFailed: 'Password reset failed',
            sending: 'Sending...',
            sendFailed: 'Send failed',
            resetting: 'Resetting...',
            passwordTooShort: 'Password must be at least 6 characters'
          },
          deleteAccount: 'Delete Account',
          deleteAccountTitle: 'Delete Account',
          deleteAccountContent: 'After deleting your account, all your data will be permanently deleted and cannot be recovered. Are you sure you want to continue?',
          confirm: 'Confirm',
          cancel: 'Cancel',
          deleting: 'Deleting...',
          deleteSuccess: 'Account Deleted',
          deleteFailed: 'Delete Failed'
        },
        deviceSuccess: {
          title: 'Add Device',
          bindingSuccess: 'Device Binding Successful',
          openExperience: 'Start 3D Printing Experience!',
          goHome: 'Return to Profile',
          bindingSuccessToast: 'Binding Successful',
          bindingFailed: 'Binding Failed'
        },
        addDevice: {
          title: 'Add Device',
          connectWifi: 'Connect WiFi',
          pleaseSelectWiFi: 'Please Select WiFi',
          scanning: 'Scanning...',
          getFailedRetry: 'Failed to get, tap to retry',
          select: 'Select',
          noWiFi: 'No WiFi',
          stopScan: 'Stop Scan',
          enterPassword: 'Please enter WiFi password',
          tipsText: 'Please ensure the home WiFi network is 2.4G network',
          networking: 'Network connecting...',
          nextStep: 'Next',
          pleaseEnterPassword: 'Please enter password'
        },
        printerIntro: {
          title: 'Printer',
          encouragementText: 'Your creation is being born, go check the printer!',
          connectionFailed: 'Device connection failed, please check network',
          idle: 'Sleeping',
          printing: 'Working',
          hungry: 'Hungry',
          error: 'Sick',
          offline: 'Lost'
        },
        printerMoreIntro: {
          title: 'Printer Settings'
        },
        printerPrint: {
          title: 'Printer Print',
          instructionTitle: 'Please follow the instructions',
          instructionText: 'In power-on state, press and hold the power button for 7 seconds until the indicator light flashes orange',
          readyButton: 'I\'m Ready'
        },
        message: {
          title: 'Message',
          prompt: 'Prompt',
          clearConfirm: 'Are you sure you want to clear all messages?'
        },
        messageSettings: {
          title: 'Message Settings',
          systemNotification: 'System Notification',
          pushNotification: 'Push Notification',
          bannerNotification: 'Banner notifications in system',
          appMessages: 'In-app Messages',
          messageReminder: 'Message Reminder',
          reminderDesc: 'After turning off, no red dot prompts will be shown',
          printStatus: 'Print Status',
          printSuccess: 'Print Success',
          printFailure: 'Print Failure',
          goToSystemSettings: 'Please go to system settings'
        },
        messageList: {
          emptyText: 'No messages',
          cleared: 'All messages cleared'
        },
        loginMixwareAgreement: {
          title: 'mixware User Agreement',
          section1Title: '1. mixware Service Description',
          section1Content: 'mixware is a professional 3D printing management application that provides users with comprehensive services such as model browsing, creation, and printing management. This agreement is a legal agreement between you and mixware regarding the use of this service.',
          section2Title: '2. Account Management',
          section2Content: 'Accounts registered by users in mixware belong to the users, but mixware reserves the right to manage accounts. Users may not transfer, sell, or lend accounts. If an account is found to be compromised, notify mixware immediately.',
          section3Title: '3. 3D Model Copyright',
          section3Content: 'The 3D models on the mixware platform are copyrighted by their original authors. Users can browse, download, and use models, but may not use them for commercial purposes or infringe upon the rights of the original authors. Models uploaded by users should ensure they have legitimate copyrights.',
          section4Title: '4. 3D Printer Device Management',
          section4Content: 'Users can manage connected 3D printer devices through mixware. Users should ensure device usage complies with local laws and regulations and may not be used to print prohibited items. mixware is not responsible for losses caused by improper device usage.',
          section5Title: '5. Service Fees',
          section5Content: 'mixware\'s basic services are provided free of charge, but certain advanced features may require payment. The pricing and terms of paid services are subject to mixware\'s official announcements. After purchasing paid services, refunds are not supported.',
          section6Title: '6. User Behavior Guidelines',
          section6Content: 'When using mixware services, users should comply with the following guidelines: do not post illegal, harmful, pornographic, or violent content; do not infringe upon others\' intellectual property rights; do not interfere with or disrupt normal service operations; do not use the service for fraud or other illegal activities.',
          section7Title: '7. Intellectual Property',
          section7Content: 'All content on the mixware platform, including but not limited to software, designs, text, images, videos, etc., is protected by intellectual property law. Without mixware\'s written permission, users may not copy, distribute, modify, or use for commercial purposes.',
          section8Title: '8. Disclaimer',
          section8Content: 'mixware is not responsible for the following situations: print failures due to improper user operations; service interruptions due to device failures or network issues; quality issues of third-party content or services; force majeure events.',
          section9Title: '9. Service Termination',
          section9Content: 'mixware has the right to terminate or suspend services under the following circumstances: users violate this agreement; user behavior damages mixware or other users\' interests; legal requirements or other necessary situations. After service termination, user accounts will be frozen or deleted.',
          section10Title: '10. Dispute Resolution',
          section10Content: 'Any disputes arising from this agreement should first be resolved through friendly negotiations. If negotiations fail, either party may file a lawsuit with the people\'s court in mixware\'s location.',
          section11Title: '11. Contact Information',
          section11Content: 'If you have any questions or suggestions about this agreement, please contact us through the following methods: Email: support@mixware.com; Phone: 400-XXX-XXXX.'
        },
        loginPrivacy: {
          title: 'Privacy Notice',
          section1Title: '1. Information Collection',
          section1Content: 'We may collect your personal information, including but not limited to: email address, device information, usage logs, etc. This information is used to provide and improve our services.',
          section2Title: '2. Information Usage',
          section2Content: 'We use collected information to: provide, maintain and improve our services; process your requests and transactions; send you relevant notifications; protect our services and users.',
          section3Title: '3. Information Sharing',
          section3Content: 'We will not sell, trade or transfer your personal information to third parties unless we obtain your explicit consent or as required by law. We may share necessary information with trusted third-party service providers to provide services.',
          section4Title: '4. Information Security',
          section4Content: 'We take reasonable technical and administrative measures to protect your personal information security, including data encryption, access control, security audits, etc. However, please note that no internet transmission or storage method is 100% secure.',
          section5Title: '5. Cookie Usage',
          section5Content: 'We use cookies and similar technologies to improve user experience, analyze usage, provide personalized content. You can manage cookie preferences through browser settings.',
          section6Title: '6. Your Rights',
          section6Content: 'You have the right to access, correct, delete your personal information, as well as object to or restrict certain processing. You can exercise these rights by contacting us.',
          section7Title: '7. Children\'s Privacy',
          section7Content: 'Our services are not directed to children under 13 years of age. We do not intentionally collect personal information from children under 13. If such cases are discovered, we will delete them immediately.',
          section8Title: '8. Privacy Policy Updates',
          section8Content: 'We may update this privacy policy from time to time. Updated policies will be published on this page with revision dates. Significant changes will be notified to you through other means.'
        },
        loginUserAgreement: {
          title: 'User Agreement',
          section1Title: '1. Terms of Service',
          section1Content: 'Welcome to use mixware services. Before using this service, please read and understand this user agreement carefully. Using this service indicates that you agree to all terms of this agreement.',
          section2Title: '2. User Registration',
          section2Content: 'Users must provide true and accurate personal information during registration. Users are responsible for maintaining the confidentiality of their account and password, and for all activities occurring under that account.',
          section3Title: '3. Service Usage',
          section3Content: 'Users promise not to use this service for any illegal or inappropriate activities, including but not limited to posting illegal information, infringe upon others\' intellectual property rights, etc.',
          section4Title: '4. Privacy Protection',
          section4Content: 'We will take reasonable technical measures to protect the security of users\' personal information, but will not be liable for information leaks caused by force majeure or third-party reasons.',
          section5Title: '5. Disclaimer',
          section5Content: 'This service is provided "as is" without guarantee of continuity, timeliness, security, or freedom from errors. Risks arising from user\'s use of this service are borne by the user.',
          section6Title: '6. Agreement Modifications',
          section6Content: 'We reserve the right to modify this agreement at any time. The modified agreement becomes effective upon publication. If users disagree with the modified agreement, they should stop using this service.',
          section7Title: '7. Applicable Law',
          section7Content: 'The establishment, execution, and interpretation of this agreement are governed by the laws of the People\'s Republic of China. In case of disputes, both parties should resolve them through friendly negotiation.'
        },
        commentList: {
          title: 'All Comments',
          comments: 'comments',
          sortByTime: 'Sort by Time',
          sortByLikes: 'Sort by Likes',
          sortByReplies: 'Sort by Replies',
          reply: 'Reply',
          delete: 'Delete',
          replyTo: 'Reply to',
          placeholder: 'Say something...',
          inputPlaceholder: 'Write something...',
          publish: 'Publish',
          deleteConfirm: 'Confirm Delete',
          deleteContent: 'Are you sure you want to delete this comment?',
          deleteSuccess: 'Delete successful',
          deleteFailed: 'Delete failed',
          publishSuccess: 'Publish successful',
          publishFailed: 'Publish failed',
          justNow: 'Just now',
          minutesAgo: 'minutes ago',
          hoursAgo: 'hours ago',
          daysAgo: 'days ago',
          imageUploadInDev: 'Image upload feature under development'
        },
        followList: {
          title: 'Follow List',
          followingTitle: 'Following List',
          followersTitle: 'Followers List',
          following: 'Following',
          followers: 'Followers',
          follow: '+ Follow',
          followed: 'Followed',
          mutualFollow: 'Mutual Follow',
          noFollowing: 'Not following anyone yet',
          noFollowers: 'No followers yet',
          noDescription: 'This person is lazy and wrote nothing',
          followSuccess: 'Follow successful',
          unfollowSuccess: 'Unfollow successful',
          operationFailed: 'Operation failed'
        }
      }
      
      return state.language === 'en' ? en : zh
    }
  },
  
  actions: {
    loadLanguage(updateTabBar = true) {
      try {
        const stored = uni.getStorageSync('appLanguage')
        if (stored === 'en' || stored === 'zh') {
          this.language = stored
        }
        // 加载语言后更新TabBar（可选）
        if (updateTabBar) {
          this.updateTabBar()
        }
      } catch (e) {
        this.language = 'zh'
      }
    },
    
    updateTabBar() {
      const texts = this.texts
      // 只在 TabBar 页面更新
      const pages = getCurrentPages()
      const currentPage = pages[pages.length - 1]
      const tabBarPages = ['pages/explore/explore/explore', 'pages/create/create/create', 'pages/profile/profile']
      if (!currentPage || !tabBarPages.includes(currentPage.route)) {
        return
      }
      try {
        uni.setTabBarItem({
          index: 0,
          text: texts.tabBar.explore
        })
        uni.setTabBarItem({
          index: 1,
          text: texts.tabBar.create
        })
        uni.setTabBarItem({
          index: 2,
          text: texts.tabBar.profile
        })
      } catch (e) {
        console.warn('更新TabBar文本失败:', e)
      }
    },
    
    setLanguage(lang) {
      this.language = lang
      try {
        uni.setStorageSync('appLanguage', lang)
        // 更新TabBar文本
        this.updateTabBar()
      } catch (err) {
        console.warn('保存语言设置失败:', err)
      }
    },
    
    toggleLanguage() {
      const newLang = this.language === 'zh' ? 'en' : 'zh'
      this.setLanguage(newLang)
      return newLang
    }
  }
})